### ISSUE TITLE
关于移动的部分

### ISSUE THREAD

**Issue by beyoungglh** [tianbot/rosecho#1]
想问下这个移动的部分怎么开始啊？是用什么平台？纯仿真？

**Comment by tianb03** [comment]
暂时我们提供的Demo是turtlebot stage的仿真。用ROS的话很容易移植到任何移动平台上。


----------
Q: May I ask that how to start with the navigation? Which platform to use or simulation only?
A: We only offer a simulation demo currently. There wont take much effort to transfer the code to any other mobile platform.
